language: generic

os:
  - linux
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.anaconda.com/miniconda/Miniconda3-latest"
    - PYTHON="3"
    - secure: "WI5FlsxeXA0AR3xcCdDx4d9LfVAYMOpM/AJKa7Mt3E6kQtQRg9u9SPQWiRtcj56R0dITsfkqO8HrUqBLxFyK8ovYboXi00ldxksyyLGAy23PZrgXa1AqDZ7n8IPt5YzBTAQDN8/N77uCLR8BgoYmWUUE0rJO4HeWCmlYB/mAan01PYCmtMnS6oFbGG3icrjtil59Mc5pVr+G0lmTXHlr5+KDfEMsrIs3bP/0vKzs0GXXOhIwKtqtMjAmlR/chBUpxhP4pqQp70zSKdXd3rSLIwsZIEJ6yps/ucrQAFxBdeRlckwEQ7Y0JIwO8WUKEaqGAgZRSIY6iJDCLb+qMy9zJSis91q3iNjA1t8tqzDjiHc3Z3iaaldIw3h171QmhRvGPjZnTd/UsaZhrLxphVvl2mooTCkFUmf1yQY3bY4D+HEYMj3j0C35n33GzW71yXhuINrqW5nj6PphINp2+EJF/tYLXXV5w8vhOADFdGp085Rs72pQ0tYzWiDZq7ityKxe+taBHkg1bg/Or4XNOuMaNWNqwlNQZ6+0Oxobx7td8U/XTyWS/+orlr9t1MhU+Rwgto03yE9O49YmtRfCqJoXEEYCN7Zej+LPHXWvAe4eSCQInuWn4PLcWf9UoL+fkmrY1b4jTDUu/2y+cWfR+vUPR+SVZJbajMWLyUfg+0KSyCU="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda create -n test python=$PYTHON conda-build anaconda-client
  - source activate test
  - conda info -a

script:
  - conda build ./recipe

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --token=-
